### ISSUE TITLE
How to prepare CC3M_data

### ISSUE THREAD

**Issue by nessessence** [SivanDoveh/TSVLC#1]
I wonder what is your data format, e.g., what is your folder structure and how images are stored?
and how do you prepare "train_with_cap.csv"  and "val_with_cap.csv"  (https://ai.google.com/research/ConceptualCaptions/download only provides .tsv files ) 

Thanks

**Comment by jonghakim35** [comment]
Hi, did you figure out how to get "train_with_cap.csv" and "val_with_cap.csv" files? I'm facing the same issue.

**Comment by SivanDoveh** [comment]
Hi! I uploaded the files to the google drive: https://drive.google.com/drive/folders/1WosT_kdam1ymWjVSK2ezyydLoqmm0LdX
