### ISSUE TITLE
Questions about the mean accuracy.

### ISSUE THREAD

**Issue by yestinl** [SivanDoveh/TSVLC#2]
I wonder that how to calculate the mean value of the Objects/Attributes/Relation. I found the commented code in the *https://github.com/SivanDoveh/TSVLC/blob/main/src/vl_checklist/evaluate_vl.py* which shows the average results of Attributes is calculated by **the numbers of the test items (e.g. color, material) of Attributes**  but **not the numbers of the data of Attributes**.  I'm confused and want to confirm that if any bugs here?

```
def start(self):
        avg = 0
        for data_type in self.types:
            results = self.eval(data_type=data_type)
        #     avg += results
        # avg = avg / len(self.types)
        # if self.args.save_logs:
        #     if self.tb_writer is not None:
        #         self.tb_writer.add_scalar(f"val/{self.types[0].split('/')[0]}_avg_eval", avg, self.epoch)
        #         logging.info(
        #             f" AVG {self.epoch}: {self.types[0].split('/')[0]}_avg_eval {avg}")
```

**Comment by SivanDoveh** [comment]
Hi, I calculated the results for all Objects, 5 Attributes, and two relations as in VL CHECKLIST.
Then, I calculate the mean for each for the paper. For example: "R-action"+ "R-spatial" /2 = Relations in the paper
