### ISSUE TITLE
Question about MHA LoRA weights initialisation

### ISSUE THREAD

**Issue by vishaal27** [SivanDoveh/TSVLC#5]
In your MHA LoRA implementation, it seems like you initialise both the lora_A and lora_B weights of the QKV projectors with the xavier-uniform initialisation:
https://github.com/SivanDoveh/TSVLC/blob/a9c96ab9f635db7aa659505d7c920e1271c1da4b/src/open_clip/loralib/layers.py#L420-L434
However, in the original [LoRA paper](https://arxiv.org/pdf/2106.09685.pdf) sec 4.1, they mention that one of the LoRA weights should always be initialised with zeros while the other can be initialised randomly:
<img width="500" alt="Screenshot 2023-09-10 at 4 57 55 PM" src="https://github.com/SivanDoveh/TSVLC/assets/21314772/e534e4f6-84e5-4d5a-b0d2-b95aecacfd5d">
(see also the discussion here from the authors: https://github.com/microsoft/LoRA/issues/114)

Therefore, should this implementation not be corrected to initialise one of the projector matrices to zeros while keeping the others as is, for example:
```python
    def _reset_parameters(self):
        if self._qkv_same_embed_dim:
            xavier_uniform_(self.in_proj_weight)
            xavier_uniform_(self.in_proj_weight_lora_A)
            constant_(self.in_proj_weight_lora_B, 0.)
        else:
            xavier_uniform_(self.q_proj_weight)
            xavier_uniform_(self.k_proj_weight)
            xavier_uniform_(self.v_proj_weight)
            xavier_uniform_(self.q_proj_weight_lora_A)
            xavier_uniform_(self.k_proj_weight_lora_A)
            xavier_uniform_(self.v_proj_weight_lora_A)
            constant_(self.q_proj_weight_lora_B, 0.)
            constant_(self.k_proj_weight_lora_B, 0.)
            constant_(self.v_proj_weight_lora_B, 0.)
```

Please let me know if I understood your implementation correctly, and if there are any things I'm missing. I would also be curious to know how much of a difference this initialisation actually makes in practice. Thanks :)

**Comment by leokarlin** [comment]
thanks for your comment, indeed zero init is interesting as it would start the tuning from the original model.
You are more than welcome to try it and let us know if you observe any significant improvements. Thanks!
