### ISSUE TITLE
request the script for zero-shot evaluation

### ISSUE THREAD

**Issue by nessessence** [SivanDoveh/TSVLC#9]
Thanks for such an interesting work!

I'd like to evaluate my trained model and reproduce the score.
The paper mentions that you use https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC to compute the score. However, lots of modification is needed to run the code with your model.
Could you share the code or a method that you use to compute the zero-shot score?

Thanks

**Comment by SivanDoveh** [comment]
Hi, you just need to calculate it the same way you will calculate for CLIP (just use our libraries)

**Comment by hiker-lw** [comment]
> Hi, you just need to calculate it the same way you will calculate for CLIP (just use our libraries)

Hi, thanks for your wonderful work! I found that the avg score of 21 zero-shot tasks I produced using your provided checkpoint is very different with the results reported in your paper (10% in differences). Could you please provide some details about how you get the results?  I using the Elevater toolkit to reproduce it. Thanks very much!

**Comment by SivanDoveh** [comment]
Hi sure,
I can't share the exact code because it uses internal tools, but:
When loading my model, you should use the open_clip lib we have. It is supposed to look like this:
(in your Elevater_Toolkit_IC/vision_benchmark/evaluation/feature.py)
```
from open_clip.openai import load_openai_model
...
def get_model(config, feature_type='image'):
...
rank = 4
model = load_openai_model(model_type, jit=False, lora=rank)
```

I hope it helps!

**Comment by hiker-lw** [comment]
Hello, thanks for you reply!!!

**Comment by hiker-lw** [comment]
Hello, thanks for your reply!
When loading your checkpoints, I use your code below (```open_clip_tsvlc``` is the package you provided in github). 
```
import open_clip_tsvlc
model, _, _ = open_clip_tsvlc.create_model_and_transforms('ViT-B-32', pretrained=ckpt_path, lora=4, device=torch.device("cuda"))
```
The accuracy on compositional benchmark is within the normal margin of error, but the accuracy on  [Elevater_Toolkit_IC](https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC) is very different from the results you report in the paper (CLIP basline 0.57 vs. TSVLC 0.50). Can you check if there is any problem with this way to load your model?

**Comment by SivanDoveh** [comment]
Can you give some more information about the results you get per dataset? I can try to help you with the debug

**Comment by hiker-lw** [comment]
Thanks for your reply sincerely!!!
The fine-grained results on [Elevater](https://github.com/Computer-Vision-in-the-Wild/Elevater_Toolkit_IC) are as follows:
```
checkpoint: TSVLC_cc3m_rb_neg_epoch_5
{'rendered-sst2': 0.59363, 'fer-2013': 0.389524, 'oxford-iiit-pets': 0.77498, 'voc-2007-classification': 0.838427, 'resisc45_clip': 0.511071, 'dtd': 0.33883, 'imagenet-1k': 0.51112, 'gtsrb': 0.221219, 'cifar-100': 0.6139, 'eurosat_clip': 0.3812, 'caltech-101': 0.802557, 'food-101': 0.74495, 'hateful-memes': 0.584356, 'oxford-flower-102': 0.496732, 'country211': 0.141232, 'cifar-10': 0.8939, 'fgvc-aircraft-2013b-variants102': 0.094848, 'kitti-distance': 0.303797, 'stanford-cars': 0.391742, 'patch-camelyon': 0.613556, 'mnist': 0.3018}
Average accuracy:  0.5020652857142858
```

```
checkpoint: TSVLC_cc3m_llm_and_rb_negs_epoch_5
{'rendered-sst2': 0.606809, 'fer-2013': 0.43494, 'oxford-iiit-pets': 0.772854, 'voc-2007-classification': 0.836752, 'resisc45_clip': 0.524127, 'dtd': 0.36117, 'imagenet-1k': 0.5203, 'gtsrb': 0.239509, 'cifar-100': 0.6224, 'eurosat_clip': 0.375, 'caltech-101': 0.798901, 'food-101': 0.749901, 'hateful-memes': 0.571042, 'oxford-flower-102': 0.506405, 'country211': 0.14327, 'cifar-10': 0.8933, 'fgvc-aircraft-2013b-variants102': 0.093957, 'kitti-distance': 0.2827, 'stanford-cars': 0.399826, 'patch-camelyon': 0.669281, 'mnist': 0.2876}
Average accuracy:  0.5090497142857143
```
I'm not sure where the issue lies, and I sincerely hope you can help check it out.
